version: '3'

services:
    app:
        build: .
        user: "1000"
        restart: unless-stopped
        volumes:
            - .:/var/www/html
            - .user.ini:/usr/local/etc/php/conf.d/custom.php.ini:ro
        networks:
            - laravel

    nginx:
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
            - "1001:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:5.7
        restart: unless-stopped
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: false
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: ${DB_HOST}
            # PMA_USER: ${DB_USERNAME}
            # PMA_PASSWORD: ${DB_PASSWORD}
        ports:
            - "1002:80"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
        driver: local
